#!/bin/bash -e

# Settings
REPO_PATH=git@github.com:lreis2415/PyGeoC.git
HTML_PATH=docs/_build/html
COMMIT_USER="crazyzlj"
COMMIT_EMAIL="crazyzlj@gmail.com"
CHANGESET=$(git rev-parse --verify HEAD)

# Get a clean version of the HTML documentation repo.
rm -rf ${HTML_PATH}
mkdir -p ${HTML_PATH}
git clone -b gh-pages "${REPO_PATH}" --single-branch ${HTML_PATH}

# rm all the files through git to prevent stale files.
cd ${HTML_PATH}
git rm -rf .
cd -

# Generate the HTML documentation.
cd docs
make html
echo "Docs generated done!"
cd -
# copy .nojekyll to html dir
cp .nojekyll ${HTML_PATH}
# Create and commit the documentation repo.
cd ${HTML_PATH}
git add .
git config user.name "${COMMIT_USER}"
git config user.email "${COMMIT_EMAIL}"
git commit -m "Automated docs for changeset ${CHANGESET}."

# contains(string, substring)
#
# Returns 0 if the specified string contains the specified substring,
# otherwise returns 1.
# https://stackoverflow.com/questions/2829613/how-do-you-tell-if-a-string-contains-another-string-in-unix-shell-scripting
contains() {
    string="$1"
    substring="$2"
    if test "${string#*$substring}" != "$string"
    then
        return 0    # $substring is in $string
    else
        return 1    # $substring is not in $string
    fi
}

ANY_CHANGES=$(git commit -m "Any changes?")
contains "$ANY_CHANGES" "no changes added to commit" && git push origin gh-pages
cd -
